spring.application.name=janken
# データベースのURL（springdbは作成したDB名）
spring.datasource.url=jdbc:mysql://localhost:3306/jankendb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Tokyo


# MySQLのユーザーとパスワード（rootは管理者）
spring.datasource.username=root
spring.datasource.password=BTCS-2000k

# 実行するSQLを表示（確認用）
spring.jpa.show-sql=true