spring.application.name=janken

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=${PORT:8080}

# 死んだ接続を除外するためのテストクエリ (TiDB無料プラン用）
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.validation-timeout=5000

# TiDB が切る前に Hikari が捨てる (TiDB無料プラン用）
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.keepalive-time=30000

# プール枯渇対策 (TiDB無料プラン用）
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=20

# コネクションリークの検出（原因特定用） (TiDB無料プラン用）
spring.datasource.hikari.leak-detection-threshold=2000

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# HTTP レスポンスが返るまで JPA の DB コネクションを握り続けるのを禁止する設定。TiDB無料プランにおけるコネクションプール枯渇問題解消
spring.jpa.open-in-view=false



mybatis.type-handlers-package=com.example.app

logging.level.com.mysql.cj=DEBUG