spring.application.name=janken
# データベースのURL（springdbは作成したDB名）
spring.datasource.url=jdbc:mysql://localhost:3306/janken_dev?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Tokyo


# MySQLのユーザーとパスワード（rootは管理者）
spring.datasource.username=devuser
spring.datasource.password=password0923

# 実行するSQLを表示（確認用）
spring.jpa.show-sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

